language: python
python:
  - "2.7"
# installing dependencies:
install:
  - pip install tornado
#  - pip install -r requirements.txt --use-mirrors
script:
  - python xmastree.py &
  - python -m server_api_tests
