language: python
python:
  - "2.6"
  - "2.7"
# installing dependencies:
install:
  - pip install tornado
  - pip install RPi.GPiO
#  - pip install -r requirements.txt --use-mirrors
before_script:
  - python xmastree.py &
  - sleep 3
script:
  - python -m server_api_tests
