language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
# installing dependencies:
install:
  - pip install -Iv tornado==2.4.1
#  - pip install -r requirements.txt --use-mirrors
before_script:
  - python xmastree.py &
  - sleep 3
script:
  - python -m server_api_tests
